POST http://localhost:8080/singup 
Content-Type: application/json

{
    "username" : "phhduc",
    "password" : "ctk43dlu",
    "fullname" : "Pham Huy Duc",
    "gender": true
}
######################################
GET http://localhost:8080/singup 
Content-Type: application/json

{
    "username": "phhduc"
}